// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILEMAP_AREA_H
#define _TILEMAP_AREA_H

extern const UINT8 TILEMAP_AREA[];
#define TILEMAP_AREA_WIDTH 8
#define TILEMAP_AREA_HEIGHT 8


#endif
